### ISSUE TITLE
make RegionColor automatic

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/fluent-xaml-theme-editor#22]
**Lastly, don’t forget to set the background color of your page to the RegionColor that you picked for your theme. It’s the only brush that won’t get set automatically.**

above statement in ReadMe, clearly indicates that RegionColor and I guess also RegionBrush are 2 resource which do not automatically applied to the app, which makes sense because these 2 names are not in SystemResources, I wanted to ask can this be fixed? I mean can the name be swapped with a resource name which i automatically applied from ThemeResource ? or more specifically what is the reason of this particular issue that this resource is named in such a way that it has to be manually applied?

**Comment by mdtauk** [comment]
To make it more automatic would require integrating it with something like Template Studio which uses the Region Colour instead of the system default brushes.

Or require a platform change where the Windows UWP team make RegionColor a thing within the system resources, and brushes that paint backgrounds be changed to use them.

For now, you just apply RegionColor as a resource to the control/page you want to use it on.

**Comment by touseefbsb** [comment]
got it, thnks for the clarification :)
