### ISSUE TITLE
Code behind example is problematic.

### ISSUE THREAD

**Issue by groovykool** [microsoft/fluent-xaml-theme-editor#29]
The code behind example is problematic because there is no "Dark" key in the dictionary.

Using pure XAML and setting RequestedTheme="Dark" in the page tag works fine.

Also setting this.RequestedTheme=ElementTheme.Dark; in the code behind works fine.

Can anyone explain or point to a reference for how the dark theme is actually created since the dictionary produced by the fluent-xaml-theme-editor does not have a "Dark" key.

**Comment by kikisaints** [comment]
Default and Dark are the same **dictionary**. However, setting RequestedTheme="Default" on a control or container, will instead respect whatever the system theme is (Light **or** Dark) depending.

But plopping in a:

```xaml
<ResourceDictionary x:Key="Dark">
        ...
</ResourceDictionary>
```

Instead of Default will give you the same result.

I do agree it's a bit confusing, unfortunately this tool doesn't have much control over how the XAML framework itself has set up the resource system.
